version: '3'
services:
  web:
    build:
      context: .
    environment:
      VIRTUAL_HOST: kicker-frenzy.ru
      LETSENCRYPT_HOST: kicker-frenzy.ru
      LETSENCRYPT_EMAIL: spam@onsky.ru
    networks:
      - public
    volumes:
      - ./db.sqlite:/app/db.sqlite
    expose:
      - 8080

networks:
  public:
    external:
      name: public
